Repository TechHubsAr/techhubsar, pull requests merged in 2025-02, with the labels that each got.

#13 feat: added clubdevops community
  public/data/communities.json
Labels: good first issue, community-add

#15 Add SJNHS
  public/data/communities.json
Labels: community-add

#16 [Fix] Dependencies: vulnerabilities, peer deps, types
  package-lock.json
  package.json
Labels: bug

#10 Fix: fixed some info, enhanced styling, bug fixed & more.
  app/about/page.tsx
  app/add-community/page.tsx
  app/communities/page.tsx
  app/community/[id]/page.tsx
  app/contact/page.tsx
  app/page.tsx
  components/ArgentinaMap.tsx
  components/CommunityList.tsx
  package-lock.json
  package.json
  public/data/communities.json
Labels: enhancement, community-update

#29 feat(theme): add light mode support and improve UI reliability
  app/communities/page.tsx
  app/layout.tsx
  app/page.client.tsx
  app/page.tsx
  components/AddCommunityButton.tsx
  components/ArgentinaMap.tsx
  components/CommunityList.tsx
  components/DarkModeToggle.tsx
  components/Footer.tsx
  components/Header.tsx
  components/ThemeSwitch.tsx
  components/ui/x-formerly-twitter.tsx
Labels: enhancement
